language: java
jdk:
  - oraclejdk7
before_install:
 - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
 - tar -zxf android-sdk_r22.0.1-linux.tgz
 - export ANDROID_HOME=`pwd`/android-sdk-linux
 - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
 - echo 'y' > android-sdk-linux.stdin
 - android update sdk --filter tools,platform-tools,android-14 --no-ui --force < android-sdk-linux.stdin
