language: java
jdk:
  - oraclejdk7
before_install:
 - sudo apt-get update -qq
 - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
 - curl http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz | tar zxv
 - export ANDROID_HOME=`pwd`/android-sdk-linux
 - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/17.0.0
 - echo 'y' > android-sdk-linux.stdin; android update sdk --all --no-ui --force --filter tools,platform-tools,build-tools-17.0.0,android-14 < android-sdk-linux.stdin
